version: "3"
services:
  nodejs:
    build: .
    ports:
      - "1907:1907"
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  redis:
    image: redis
    ports:
      - "6379:6379"
    depends_on:
      - mongo
